import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create schema auth; create table auth.users(id uuid primary key); create role anon; create role authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public to authenticated; grant execute on function auth.uid() to authenticated;
insert into auth.users values ('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
await db.exec(await readFile('cloud/schema.sql','utf8'));
await db.exec(`insert into public.food_tracker_members values ('11111111-1111-4111-8111-111111111111'); set role authenticated; select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);`);
const sync=async changes=>(await db.query('select public.food_tracker_sync($1::jsonb) as result',[JSON.stringify(changes)])).rows[0].result;
let result=await sync([{key:'days/2026-09-08',value:{complete:false},base_version:0}]);assert.equal(result.applied,true);
result=await sync([{key:'days/2026-09-08',value:{complete:false},base_version:0}]);assert.equal(result.applied,true);assert.equal(result.records[0].version,1);
result=await sync([{key:'days/2026-09-08',value:{complete:true},base_version:0}]);assert.equal(result.applied,false);assert.equal(result.records[0].value.complete,false);
result=await sync([{key:'days/2026-09-08',value:{complete:true},base_version:1}]);assert.equal(result.records[0].version,2);
assert.equal((await db.query('select public.food_tracker_use_ai() as allowed')).rows[0].allowed,true);
assert.equal((await db.query('select public.food_tracker_use_ai() as allowed')).rows[0].allowed,false);
await db.exec(`select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);`);
assert.equal((await db.query('select * from public.food_tracker_records')).rows.length,0);
await assert.rejects(()=>sync([]));
await db.close();console.log('OK: schema, RLS, conflitos, repetição idempotente e limite de IA.');
