'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone = value => JSON.parse(JSON.stringify(value));
const id = () => crypto.randomUUID();
const fmt = (n, digits = 0) => new Intl.NumberFormat('pt-BR', {maximumFractionDigits:digits}).format(n);
const localDate = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const shiftDate = (date, amount) => { const d = new Date(date+'T12:00:00'); d.setDate(d.getDate()+amount); return localDate(d); };
const dateLabel = date => new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const meals = ['Café da manhã','Lanche da manhã','Almoço','Lanche da tarde','Jantar'];
const labels = {label:'Rótulo transcrito',table:'Tabela de composição',estimate:'Estimativa'};
const star = '<svg class="svg-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/></svg>';
let state, revision, view = 'today', selectedDate = localDate(), busy = false, editor = null, toastTimer, undo = null;
const session = $('meta[name=session]').content;
const main = $('#main'), panel = $('#editor');
const currentDay = () => state.days[selectedDate] || {complete:false,entries:[]};
const targetFor = date => [...state.targets].sort((a,b)=>a.date.localeCompare(b.date)).filter(t=>t.date<=date).at(-1) || [...state.targets].sort((a,b)=>a.date.localeCompare(b.date))[0];
const amount = entry => ({kcal:entry.food.kcal * entry.quantity/entry.food.base, protein:(entry.food.protein ?? 0)*entry.quantity/entry.food.base});
function sum(entries) { return entries.reduce((a,e)=> {const n=amount(e);return {kcal:a.kcal+n.kcal,protein:a.protein+n.protein,unknown:a.unknown||e.food.protein===null};},{kcal:0,protein:0,unknown:false}); }
const foodById = foodId => state.foods.find(f=>f.id===foodId);
// Food identity excludes portion size; preparation and brand remain part of the name.
function parseFoodDescription(text){
 const unitPattern='(kg|quilogramas?|g|gramas?|ml|mililitros?)';
 const leading=new RegExp('^(\\d+(?:[.,]\\d+)?)\\s*'+unitPattern+'\\b\\s*(?:de\\s+)?(.+)$','i');
 const trailing=new RegExp('^(.+?)\\s*[-–(]?\\s*(\\d+(?:[.,]\\d+)?)\\s*'+unitPattern+'\\s*\\)?$','i');
 let m=text.trim().match(leading),name,quantity,unit;
 if(m){quantity=Number(m[1].replace(',','.'));unit=m[2];name=m[3];}
 else if((m=text.trim().match(trailing))){name=m[1];quantity=Number(m[2].replace(',','.'));unit=m[3];}
 else return {name:text.trim(),quantity:null,unit:null};
 unit=unit.toLowerCase();if(unit.startsWith('k'))quantity*=1000;
 return {name:name.trim(),quantity,unit:unit.startsWith('m')?'ml':'g'};
}
function foodIdentity(name){return parseFoodDescription(name).name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(w=>w!=='de').sort().join(' ');}
function sameFood(food,list=state.foods){return list.find(f=>f.id!==food.id&&f.unit===food.unit&&foodIdentity(f.name)===foodIdentity(food.name));}
function normalizeFoodReference(food){
 const result={...food,name:parseFoodDescription(food.name).name};
 if(['g','ml'].includes(food.unit)&&food.base>0){result.base=100;result.kcal=food.kcal*100/food.base;result.protein=food.protein===null?null:food.protein*100/food.base;}
 return result;
}
function reuseFood(food,quantity){
 const meal=editor?.returnMeal||editor?.meal||meals[0];editor={meal};openQuantity(food);
 if(quantity>0){$('#quantity-form [name=quantity]').value=quantity;quantityPreview();}
 toast('Alimento já cadastrado. Ajuste a quantidade e adicione à refeição.');
}
function savedFoodResult(description,output){
 const parsed=parseFoodDescription(description);if(!parsed.quantity||parsed.quantity>100000)return false;
 const words=foodIdentity(parsed.name).split(' ').filter(Boolean);if(!words.length)return false;
 const matches=state.foods.filter(f=>f.unit===parsed.unit&&words.every(w=>foodIdentity(f.name).split(' ').includes(w)));
 if(!matches.length)return false;
 editor.savedQuantity=parsed.quantity;
 output.innerHTML=`<p>Já tenho uma referência. Escolha o alimento e confira o preparo:</p>${matches.map(f=>`<button type="button" class="result" data-ai="reuse" data-id="${escape(f.id)}"><span>${escape(f.name)}<small>${fmt(parsed.quantity,2)} ${escape(f.unit)} · ${labels[f.confidence]}</small></span><strong>${fmt(amount({food:f,quantity:parsed.quantity}).kcal)} kcal</strong></button>`).join('')}<p class="help">A quantidade será registrada na refeição, sem criar outro alimento. Se for outro preparo ou marca, detalhe na busca.</p>`;
 return true;
}
function mealOptions(selected) { const list=[...new Set([...meals,...currentDay().entries.map(e=>e.meal),selected].filter(Boolean))];return list.map(m=>`<option ${m===selected?'selected':''}>${escape(m)}</option>`).join(''); }
const badge = food => `<span class="badge ${food.confidence==='estimate'?'estimate':''}">${labels[food.confidence]}</span>`;
const errorSlot = '<p class="error" id="form-error" role="alert"></p>';
function formError(error) {const el=$('#form-error'); if(el)el.textContent=error.message || error;else toast(error.message||error);}
function toast(message, withUndo = false) {clearTimeout(toastTimer);const el=$('#toast');el.innerHTML=`${escape(message)}${withUndo?'<button id="undo">Desfazer</button>':''}`;el.hidden=false;toastTimer=setTimeout(()=>{el.hidden=true;},withUndo?14000:6500);}
function confirmAction(title,message) { const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;return new Promise(resolve=>{d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true});d.showModal();}); }
async function api(path, payload) { if(window.FoodCloud?.enabled)return FoodCloud.api(path,payload); const response=await fetch('/api/'+path,{method:payload?'POST':'GET',headers:{'X-Session':session,...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined}); const data=await response.json();if(!response.ok)throw new Error(data.error || 'Não foi possível concluir. Tente novamente.');return data; }
async function change(fn,message='Salvo',allowUndo=false) {
  if(busy)return false;
  const before=clone(state),next=clone(state);busy=true;$('#save-status').textContent='Salvando…';
  try {fn(next);const result=await api('save',{revision,state:next,baseState:before});state=result.state;revision=result.revision;undo=allowUndo?before:null;render();updateSaveStatus();toast(message,allowUndo);return true;}
  catch(error){formError(error);$('#save-status').textContent='Alteração não salva';return false;}
  finally{busy=false;}
}
function dayIn(s){return s.days[selectedDate] || (s.days[selectedDate]={complete:false,entries:[]});}
function closeEditor(){panel.hidden=true;panel.innerHTML='';editor=null;$('#main').removeAttribute('aria-hidden');if(window.FoodCloud?.enabled)refreshCloudView();}
function editorFrame(title,body) {panel.hidden=false;panel.innerHTML=`<div class="editor-head"><h2>${escape(title)}</h2><button data-act="close" aria-label="Fechar painel">×</button></div>${body}`;setTimeout(()=>panel.querySelector('input,select')?.focus(),0);}
function render() {
  $$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  ({today:renderToday,foods:renderFoods,recipes:renderRecipes,history:renderHistory,settings:renderSettings})[view]();
}
function renderToday(){
 const day=currentDay(),t=targetFor(selectedDate),n=sum(day.entries),left=t.kcal-n.kcal,proteinLeft=t.protein-n.protein;
 const title=selectedDate===localDate()?'Seu dia, refeição por refeição':dateLabel(selectedDate);
 const groups=[...new Set([...meals,...day.entries.map(e=>e.meal)])];
 main.innerHTML=`<header class="page-head"><div><h1>${escape(title)}</h1><p>${new Date(selectedDate+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p></div><div class="date-control"><button data-act="prev" aria-label="Dia anterior">‹</button><input id="day-date" type="date" value="${selectedDate}" aria-label="Data do diário"><button data-act="next" aria-label="Dia seguinte">›</button></div></header>
 <section class="summary" aria-label="Resumo do dia"><div class="summary-section"><label>Calorias registradas</label><div class="metric"><strong>${fmt(n.kcal)}</strong><span>/ ${fmt(t.kcal)} kcal</span></div><progress class="${left<0?'over':''}" max="${t.kcal}" value="${Math.min(n.kcal,t.kcal)}" aria-label="Calorias em relação à meta"></progress><p>${left>=0?`Faltam <b>${fmt(left)} kcal</b> para a meta.`:`<b>${fmt(-left)} kcal</b> acima da meta.`}</p></div><div class="summary-section"><label>Proteína ${n.unknown?'· parcial':''}</label><div class="metric"><strong>${fmt(n.protein,1)}<span> g</span></strong><span>/ ${fmt(t.protein)} g</span></div><progress max="${Math.max(t.protein,1)}" value="${Math.min(n.protein,Math.max(t.protein,1))}" aria-label="Proteína em relação à meta"></progress><p>${proteinLeft>0?`Faltam <b>${fmt(proteinLeft,1)} g</b> para a meta.`:'Meta de proteína atingida.'}${n.unknown?' Há alimentos sem proteína informada.':''}</p></div></section>
 <div class="photo-shortcut"><button class="primary" data-act="photo"><svg class="svg-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5l2-2h4l2 2h4v15H4V5Z"/><circle cx="12" cy="12" r="4"/></svg> Registrar por foto</button><span class="help">Fotografe, confira e registre.</span></div><div class="day-toolbar"><div class="actions"><h2>Suas refeições</h2><span class="badge ${day.complete?'complete':''}">${day.complete?'Dia completo':'Em registro'}</span></div><button class="secondary" data-act="complete">${day.complete?'Reabrir dia':'Marcar dia completo'}</button></div>
 ${groups.map(meal=>{const entries=day.entries.filter(e=>e.meal===meal),n=sum(entries);return `<section class="meal"><div class="meal-head"><div class="meal-title"><h3>${escape(meal)}</h3>${entries.length?`<span class="meal-total">${fmt(n.kcal)} kcal</span>`:''}</div><div class="meal-actions"><button data-act="repeat" data-meal="${escape(meal)}">Repetir refeição</button><button class="secondary" data-act="add" data-meal="${escape(meal)}">+ Adicionar</button></div></div>${entries.length?entries.map(e=>`<div class="entry"><div class="entry-title">${escape(e.food.name)}<small>${labels[e.food.confidence]}</small></div><div class="numeric muted">${fmt(e.quantity,2)} ${escape(e.food.unit)}</div><div class="numeric">${fmt(amount(e).kcal)} kcal</div><div class="numeric muted">${e.food.protein===null?'—':fmt(amount(e).protein,1)+' g'}</div><button data-act="edit-entry" data-id="${e.id}">Editar</button></div>`).join(''):`<div class="empty-meal"><span>Ainda sem registros</span><span class="empty-line"></span></div>`}</section>`;}).join('')}
 <button class="text-button" data-act="extra-meal">Adicionar outra refeição</button><p class="footnote">Os totais refletem os alimentos registrados. Valores de rótulos e tabelas também têm variação; porções aproximadas e delivery aparecem como estimativas. Marque o dia completo quando terminar de registrar.</p>`;
}
function renderFoods(){main.innerHTML=`<header class="page-head"><div><h1>Meus alimentos</h1><p>Suas porções, suas marcas. Prontos para repetir.</p></div><button class="primary" data-act="new-food">+ Novo alimento</button></header><div class="toolbar"><input id="food-search" placeholder="Buscar por nome ou marca" aria-label="Buscar alimentos"><label class="muted"><input id="favorites-only" type="checkbox"> Só favoritos</label></div><div id="food-list" class="food-list"></div><p class="footnote">Confira as referências nutricionais dos seus alimentos. Editar um alimento atualiza os próximos registros e receitas; seu histórico permanece como foi registrado.</p>`;foodList();}
function foodList(){const search=$('#food-search').value.toLocaleLowerCase('pt-BR'),only=$('#favorites-only').checked;const list=state.foods.filter(f=>f.name.toLocaleLowerCase('pt-BR').includes(search)&&(!only||f.favorite));$('#food-list').innerHTML=list.length?list.map(f=>`<div class="food-row"><button class="favorite ${f.favorite?'selected':''}" data-act="favorite" data-id="${f.id}" aria-label="${f.favorite?'Remover dos':'Adicionar aos'} favoritos: ${escape(f.name)}" aria-pressed="${f.favorite}">${star}</button><div>${escape(f.name)}<small>Referência: ${fmt(f.base,2)} ${escape(f.unit)}</small></div><div>${badge(f)}</div><div class="numeric">${fmt(f.kcal)} kcal<small>${f.protein===null?'Proteína não informada':fmt(f.protein,1)+' g de proteína'}</small></div><button data-act="edit-food" data-id="${f.id}">Editar</button></div>`).join(''):'<div class="empty-state"><h2>Nenhum alimento encontrado</h2><p>Experimente outro nome ou cadastre o alimento com os dados da embalagem.</p></div>';}
function recipeTotals(r){return sum(r.items.map(i=>({food:foodById(i.foodId),quantity:i.quantity/r.servings})));}
function renderRecipes(){main.innerHTML=`<header class="page-head"><div><h1>Receitas e combinações</h1><p>Monte uma vez. Ajuste a porção quando for comer.</p></div><button class="primary" data-act="new-recipe">+ Nova receita</button></header><p class="settings-note recipe-note">Cada receita soma os ingredientes e divide pelo rendimento. Ao registrar, você pode ajustar cada quantidade antes de salvar.</p>${state.recipes.map(r=>{const n=recipeTotals(r);return `<section class="recipe-row"><div><h2>${escape(r.name)}</h2><p>${r.items.length} ingredientes · rende ${fmt(r.servings,2)} porção(ões)</p><span>${fmt(n.kcal)} kcal · ${fmt(n.protein,1)} g de proteína${n.unknown?' (parcial)':''} por porção</span></div><div class="actions"><button data-act="edit-recipe" data-id="${r.id}">Editar</button><button class="secondary" data-act="use-recipe" data-id="${r.id}">Registrar</button></div></section>`;}).join('')||'<div class="empty-state"><h2>Sua primeira receita</h2><p>Salve uma combinação que você costuma comer para registrar mais rápido.</p></div>'}<p class="footnote">Os totais são calculados pelos ingredientes e pelo rendimento informado.</p>`;}
function renderHistory(){const dates=Object.keys(state.days).sort().reverse();const complete=dates.filter(d=>d>=shiftDate(localDate(),-6)&&d<=localDate()&&state.days[d].complete);const sums=complete.map(d=>sum(state.days[d].entries));main.innerHTML=`<header class="page-head"><div><h1>Seu histórico</h1><p>Uma visão dos dias que você registrou.</p></div><button class="secondary" data-act="go-today">Voltar para hoje</button></header><div class="history-summary"><div><strong>${complete.length}/7</strong><span>Dias completos nos últimos 7 dias</span></div><div><strong>${sums.length?fmt(sums.reduce((a,n)=>a+n.kcal,0)/sums.length):'—'}</strong><span>kcal por dia completo</span></div><div><strong>${sums.length?fmt(sums.reduce((a,n)=>a+n.protein,0)/sums.length,1)+' g':'—'}</strong><span>Proteína por dia completo${sums.some(n=>n.unknown)?' · parcial':''}</span></div></div>${dates.length?`<table><thead><tr><th>Dia</th><th>Estado</th><th>Calorias / meta</th><th class="bar-cell">Em relação à meta</th><th>Proteína</th><th></th></tr></thead><tbody>${dates.map(d=>{const n=sum(state.days[d].entries),t=targetFor(d);return `<tr><td>${escape(dateLabel(d))}<small class="muted"> · ${d.slice(0,4)}</small></td><td><span class="badge ${state.days[d].complete?'complete':''}">${state.days[d].complete?'Completo':'Parcial'}</span></td><td>${fmt(n.kcal)} / ${fmt(t.kcal)}</td><td><progress class="${n.kcal>t.kcal?'over':''}" max="${t.kcal}" value="${Math.min(n.kcal,t.kcal)}" aria-label="${fmt(n.kcal)} de ${fmt(t.kcal)} kcal"></progress></td><td>${fmt(n.protein,1)} g${n.unknown?' *':''}</td><td><button data-act="open-day" data-date="${d}">Abrir</button></td></tr>`;}).join('')}</tbody></table>`:'<div class="empty-state"><h2>Seu histórico começa com a primeira refeição.</h2><p>Os dias aparecerão aqui conforme você registrar. Dias incompletos ficam fora da média.</p><button class="primary" data-act="go-today">Registrar hoje</button></div>'}<p class="footnote">A média usa apenas dias marcados como completos nos últimos sete dias corridos. Dias sem registro não contam como consumo zero. * Proteína parcial quando algum alimento não tem esse dado.</p>`;}
function renderSettings(){const t=targetFor(localDate());main.innerHTML=`<header class="page-head"><div><h1>Metas e backup</h1><p>Seu objetivo e seus dados, sob seu controle.</p></div></header><section class="section"><h2>Objetivo diário</h2><p class="settings-note">Você pode ajustar suas metas de calorias e proteína. Você pode definir uma nova meta a partir de uma data; as metas anteriores continuam no histórico.</p><form id="target-form"><div class="form-grid"><label class="field">Calorias por dia<input name="kcal" type="number" min="1" max="20000" step="1" required value="${t.kcal}"></label><label class="field">Proteína por dia (g)<input name="protein" type="number" min="0" max="1000" step="0.1" required value="${t.protein}"></label><label class="field">Vale a partir de<input name="date" type="date" required value="${localDate()}"></label></div><div class="actions"><button class="primary" type="submit">Salvar meta</button></div>${errorSlot}</form><p class="settings-note">${[...state.targets].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`${t.date.split('-').reverse().join('/')} · ${fmt(t.kcal)} kcal / ${fmt(t.protein,1)} g`).join('<br>')}</p></section><section class="section"><h2>Backup dos seus registros</h2><p class="settings-note">Crie uma cópia dos alimentos, receitas, metas e diário. Uma cópia fica na pasta do app e outra é oferecida para download, para você guardar em outro lugar.</p><div class="actions"><button class="primary" data-act="backup">Criar backup</button><button class="secondary" data-act="restore">Restaurar backup</button><input id="restore-file" type="file" accept=".json,application/json" hidden></div><p class="settings-note">A restauração substitui os dados atuais. Antes disso, o app salva uma cópia de segurança em <b>data/backups</b>. A pasta local sozinha não protege contra perda do computador.</p></section>${aiSettingsSection()}<section class="section"><h2>Como seus dados ficam guardados</h2><p class="settings-note">No executável, os dados ficam em <b>%LOCALAPPDATA%/FoodTracker/data</b>; no modo navegador, em <b>data/</b>. O diário funciona offline. Ao buscar com IA, somente a descrição digitada é enviada ao Google para gerar uma estimativa sem pesquisa web. Encerre pelo botão da barra lateral quando terminar.</p></section>`;loadAiStatus();}
function openAdd(meal=meals[0]){editor={type:'add',meal,tab:'favorites'};drawAdd();}
function drawAdd(){editorFrame('Adicionar à refeição',`<label class="field">Refeição<select id="entry-meal">${mealOptions(editor.meal)}</select></label><div class="tabs"><button data-act="add-tab" data-tab="favorites" class="${editor.tab==='favorites'?'selected':''}">Favoritos</button><button data-act="add-tab" data-tab="recent" class="${editor.tab==='recent'?'selected':''}">Recentes</button><button data-act="add-tab" data-tab="all" class="${editor.tab==='all'?'selected':''}">Todos</button><button data-act="add-tab" data-tab="recipes" class="${editor.tab==='recipes'?'selected':''}">Receitas</button></div><input id="add-search" placeholder="Ex.: 150 g de macarrão cozido" aria-label="Buscar para registrar"><div id="add-results" class="search-results"></div><div class="actions"><button data-act="new-food" class="text-button">Cadastrar alimento</button></div>`);addResults();}
function addResults(){const parsed=parseFoodDescription($('#add-search').value),search=parsed.name.toLocaleLowerCase('pt-BR');editor.searchQuantity=parsed.quantity;editor.searchUnit=parsed.unit;let list;if(editor.tab==='recipes'){list=state.recipes.filter(r=>r.name.toLocaleLowerCase('pt-BR').includes(search));$('#add-results').innerHTML=list.map(r=>`<button class="result" data-act="choose-recipe" data-id="${r.id}"><span>${escape(r.name)}<small>${r.items.length} ingredientes</small></span><span class="numeric">${fmt(recipeTotals(r).kcal)} kcal/porção</span></button>`).join('')||'<p class="muted">Nenhuma receita encontrada.</p>';return;}
 const recent=[...new Set(Object.keys(state.days).sort().reverse().flatMap(d=>state.days[d].entries.slice().reverse().map(e=>e.food.id)))];
 list=state.foods.filter(f=>foodIdentity(search).split(' ').every(w=>foodIdentity(f.name).includes(w))&&(!parsed.unit||parsed.unit===f.unit)&&(search||editor.tab==='all'||(editor.tab==='favorites'?f.favorite:recent.includes(f.id))));if(editor.tab==='recent')list.sort((a,b)=>recent.indexOf(a.id)-recent.indexOf(b.id));
 $('#add-results').innerHTML=list.map(f=>`<button class="result" data-act="choose-food" data-id="${f.id}"><span>${escape(f.name)}<small>${fmt(f.base,2)} ${escape(f.unit)} · ${labels[f.confidence]}</small></span><span class="numeric">${fmt(f.kcal)} kcal</span></button>`).join('')||'<p class="muted">Nada por aqui ainda. Busque pelo nome ou abra Todos.</p>';}
function openQuantity(food,entry=null){const meal=entry?.meal||editor?.meal||meals[0];editor={type:'quantity',food:clone(food),entryId:entry?.id,meal};editorFrame(entry?'Editar registro':food.name,`<form id="quantity-form"><label class="field">Refeição<select name="meal">${mealOptions(meal)}</select></label><p class="source">${escape(food.name)}<br>${escape(food.source)}</p>${sourceLinks(food.sources)}${badge(food)}<div class="form-grid"><label class="field full">Quantidade em ${escape(food.unit)}<input name="quantity" type="number" min="0.001" max="100000" step="any" required value="${entry?.quantity??food.base}"></label></div><div class="preview" id="quantity-preview"></div><p class="help">Referência: ${fmt(food.kcal)} kcal e ${food.protein===null?'proteína não informada':fmt(food.protein,1)+' g de proteína'} por ${fmt(food.base,2)} ${escape(food.unit)}.</p><div class="actions"><button class="primary" type="submit">${entry?'Salvar alteração':'Adicionar à refeição'}</button>${entry?'<button type="button" data-act="delete-entry">Excluir registro</button>':'<button type="button" data-act="back-add">Voltar</button>'}</div>${errorSlot}</form>`);quantityPreview();}
function quantityPreview(){const q=Number($('#quantity-form [name=quantity]').value),n=amount({food:editor.food,quantity:q});$('#quantity-preview').innerHTML=`<strong>${fmt(n.kcal)} kcal</strong> · ${editor.food.protein===null?'Proteína não informada':fmt(n.protein,1)+' g de proteína'}`;}
function openFood(food=null){const returnMeal=editor?.type==='add'?editor.meal:null;editor={type:'food',foodId:food?.id,returnMeal,sources:food?.sources||[]};const f=food||{name:'',base:100,unit:'g',kcal:'',protein:'',confidence:'label',source:'',favorite:true};editorFrame(food?'Editar alimento':'Novo alimento',`${assistantBox(food)}<p class="manual-note">Busque primeiro nos alimentos salvos ou informe o rótulo. Novos alimentos em g ou ml ficam com referência de 100; a quantidade consumida vai na refeição.</p><form id="food-form"><div class="form-grid"><label class="field full">Nome e marca<input name="name" maxlength="240" required value="${escape(f.name)}" placeholder="Ex.: arroz branco • cozido"></label><label class="field">Porção de referência<input name="base" type="number" min="0.001" max="100000" step="any" required value="${f.base}"></label><label class="field">Unidade<select name="unit">${[...new Set(['g','ml','unidade','fatia','porção','barra','pacote','colher de sopa',f.unit])].map(u=>`<option ${u===f.unit?'selected':''}>${escape(u)}</option>`).join('')}</select></label><label class="field">Calorias nessa porção<input name="kcal" type="number" min="0" max="100000" step="any" required value="${f.kcal}"></label><label class="field">Proteína nessa porção (g)<input name="protein" type="number" min="0" max="100000" step="any" value="${f.protein??''}" placeholder="Opcional"></label><label class="field full">Tipo de referência<select name="confidence">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${f.confidence===k?'selected':''}>${v}</option>`).join('')}</select></label><label class="field full">Origem dos valores<input name="source" maxlength="500" required value="${escape(f.source)}" placeholder="Ex.: rótulo da embalagem de 500 g"><span class="help">Para arroz e massas, indique cru ou cozido no nome. Deixe proteína vazia se não souber.</span></label><label class="field full"><span><input name="favorite" type="checkbox" ${f.favorite?'checked':''}> Deixar nos favoritos</span></label></div><div class="actions"><button class="primary" type="submit">Salvar alimento</button></div>${errorSlot}</form>`);}
function openRecipe(recipe=null){if(!state.foods.length){toast('Cadastre um alimento antes de montar uma receita.');openFood();return;}editor={type:'recipe',draft:clone(recipe||{id:id(),name:'',servings:1,items:[{foodId:state.foods[0]?.id,quantity:1}]})};drawRecipe();}
function ingredientRows(items,editableFoods=false){return items.map((item,i)=>{const f=foodById(item.foodId);return `<div class="ingredient" data-index="${i}">${editableFoods?`<select aria-label="Ingrediente ${i+1}" data-field="foodId">${state.foods.map(food=>`<option value="${food.id}" ${food.id===item.foodId?'selected':''}>${escape(food.name)} (${escape(food.unit)})</option>`).join('')}</select>`:`<span>${escape(f.name)}<br><small>${escape(f.unit)}</small></span>`}<input type="number" min="0.001" max="100000" step="any" required value="${item.quantity}" data-field="quantity" aria-label="Quantidade de ${escape(f.name)} em ${escape(f.unit)}">${editableFoods?`<button type="button" data-act="remove-ingredient" data-index="${i}" aria-label="Remover ingrediente">×</button>`:'<span></span>'}</div>`;}).join('');}
function collectRecipe(){const f=$('#recipe-form');editor.draft.name=f.elements.name.value;editor.draft.servings=Number(f.elements.servings.value);editor.draft.items=$$('.ingredient',f).map(row=>({foodId:$('[data-field=foodId]',row).value,quantity:Number($('[data-field=quantity]',row).value)}));}
function drawRecipe(){const r=editor.draft;editorFrame('Montar receita',`<form id="recipe-form"><div class="form-grid"><label class="field full">Nome da receita<input name="name" required maxlength="240" value="${escape(r.name)}" placeholder="Ex.: meu café da manhã"></label><label class="field full">Rendimento em porções<input name="servings" type="number" min="0.001" max="10000" step="any" required value="${r.servings}"><span class="help">Informe todos os ingredientes da receita inteira. O total será dividido pelo rendimento.</span></label></div><h3 class="section">Ingredientes da receita inteira</h3>${ingredientRows(r.items,true)}<button type="button" class="text-button" data-act="add-ingredient">+ Adicionar ingrediente</button><div class="preview" id="recipe-preview"></div><div class="actions"><button class="primary" type="submit">Salvar receita</button></div>${errorSlot}</form>`);recipePreview();}
function recipePreview(){collectRecipe();const r=editor.draft;if(r.servings>0){const n=recipeTotals(r);$('#recipe-preview').innerHTML=`<strong>${fmt(n.kcal)} kcal</strong> · ${fmt(n.protein,1)} g de proteína${n.unknown?' (parcial)':''} por porção`;}else $('#recipe-preview').textContent='Informe o rendimento.';}
function useRecipe(recipeId){const r=state.recipes.find(r=>r.id===recipeId);const meal=editor?.meal||meals[0];editor={type:'useRecipe',recipeId,meal,items:r.items.map(i=>({...i,quantity:i.quantity/r.servings}))};editorFrame('Registrar receita',`<form id="use-recipe-form"><h3>${escape(r.name)}</h3><p class="source">As quantidades abaixo correspondem a uma porção. Ajuste o que você realmente consumiu.</p><label class="field">Refeição<select name="meal">${mealOptions(meal)}</select></label><label class="field section">Porções<input name="portions" type="number" min="0.001" max="10000" step="any" value="1" required></label><div id="use-ingredients">${ingredientRows(editor.items)}</div><div class="preview" id="use-preview"></div><p class="help">Alterar o número de porções recalcula os ingredientes pela receita salva.</p><div class="actions"><button class="primary" type="submit">Adicionar à refeição</button></div>${errorSlot}</form>`);usePreview();}
function collectUse(){editor.items=$$('.ingredient',$('#use-recipe-form')).map((row,i)=>({foodId:editor.items[i].foodId,quantity:Number($('[data-field=quantity]',row).value)}));}
function usePreview(){collectUse();const n=sum(editor.items.map(i=>({food:foodById(i.foodId),quantity:i.quantity})));$('#use-preview').innerHTML=`<strong>${fmt(n.kcal)} kcal</strong> · ${fmt(n.protein,1)} g de proteína${n.unknown?' (parcial)':''}`;}
function openRepeat(meal){editor={type:'repeat',meal};const dates=Object.keys(state.days).filter(d=>d!==selectedDate&&state.days[d].entries.some(e=>e.meal===meal)).sort().reverse();editorFrame('Repetir refeição',`<p class="source">Copiar ${escape(meal)} para ${escape(dateLabel(selectedDate))}. Você poderá editar cada alimento depois.</p><div class="search-results">${dates.map(d=>{const entries=state.days[d].entries.filter(e=>e.meal===meal);return `<button class="result" data-act="copy-meal" data-date="${d}"><span>${escape(dateLabel(d))} · ${d.slice(0,4)}<small>${entries.length} alimento(s)</small></span><span>${fmt(sum(entries).kcal)} kcal</span></button>`;}).join('')||'<p class="muted">Ainda não há essa refeição em outro dia. Registre uma vez para poder repetir.</p>'}</div>`);}
document.addEventListener('click',async event=>{
 const nav=event.target.closest('[data-view]');if(nav){view=nav.dataset.view;closeEditor();render();return;}
 const undoButton=event.target.closest('#undo');if(undoButton&&undo){const previous=clone(undo);await change(s=>{Object.keys(s).forEach(k=>delete s[k]);Object.assign(s,previous);},'Exclusão desfeita');return;}
 const button=event.target.closest('[data-act]');if(!button)return;const a=button.dataset.act,foodId=button.dataset.id;
 if(busy)return;
 switch(a){
 case 'close':closeEditor();break;
 case 'prev':case 'next':selectedDate=shiftDate(selectedDate,a==='prev'?-1:1);closeEditor();render();break;
 case 'go-today':selectedDate=localDate();view='today';closeEditor();render();break;
 case 'open-day':selectedDate=button.dataset.date;view='today';closeEditor();render();break;
 case 'complete':await change(s=>{const d=dayIn(s);d.complete=!d.complete;},currentDay().complete?'Dia reaberto':'Dia marcado como completo');break;
 case 'add':openAdd(button.dataset.meal);break;
 case 'extra-meal':editor={type:'extra'};editorFrame('Outra refeição',`<form id="extra-form"><label class="field">Nome da refeição<input name="meal" required maxlength="80" placeholder="Ex.: pós-treino"></label><div class="actions"><button class="primary">Continuar</button></div></form>`);break;
 case 'repeat':openRepeat(button.dataset.meal);break;
 case 'copy-meal':{const entries=clone(state.days[button.dataset.date].entries.filter(e=>e.meal===editor.meal));if(await change(s=>{const d=dayIn(s);d.entries.push(...entries.map(e=>({...e,id:id()})));d.complete=false;},'Refeição copiada'))closeEditor();break;}
 case 'new-food':openFood();break;
 case 'edit-food':openFood(foodById(foodId));break;
 case 'favorite':{const search=$('#food-search')?.value,only=$('#favorites-only')?.checked;await change(s=>{const f=s.foods.find(f=>f.id===foodId);f.favorite=!f.favorite;},'Favoritos atualizados');if(search!==undefined){$('#food-search').value=search;$('#favorites-only').checked=only;foodList();}break;}
 case 'add-tab':editor.meal=$('#entry-meal').value;editor.tab=button.dataset.tab;drawAdd();break;
 case 'choose-food':editor.meal=$('#entry-meal').value;{const f=foodById(foodId),q=editor.searchUnit===f.unit?editor.searchQuantity:null;reuseFood(f,q);}break;
 case 'choose-recipe':editor.meal=$('#entry-meal').value;useRecipe(foodId);break;
 case 'back-add':openAdd(editor.meal);break;
 case 'edit-entry':{const e=currentDay().entries.find(e=>e.id===foodId);openQuantity(e.food,e);break;}
 case 'delete-entry':{const entryId=editor.entryId;if(await change(s=>{const d=dayIn(s);d.entries=d.entries.filter(e=>e.id!==entryId);d.complete=false;},'Registro excluído',true))closeEditor();break;}
 case 'new-recipe':openRecipe();break;
 case 'edit-recipe':openRecipe(state.recipes.find(r=>r.id===foodId));break;
 case 'use-recipe':useRecipe(foodId);break;
 case 'add-ingredient':collectRecipe();editor.draft.items.push({foodId:state.foods[0].id,quantity:state.foods[0].base});drawRecipe();break;
 case 'remove-ingredient':collectRecipe();editor.draft.items.splice(Number(button.dataset.index),1);drawRecipe();break;
 case 'backup':try{const result=await api('backup',{}),blob=new Blob([JSON.stringify(result.state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=result.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast(window.FoodCloud?.enabled?'Backup pronto para guardar.':'Backup salvo em data/backups. Download também iniciado.');}catch(e){toast(e.message);}break;
 case 'restore':$('#restore-file').click();break;
 }
});
document.addEventListener('input',event=>{const t=event.target;if(t.id==='food-search')foodList();if(t.id==='add-search')addResults();if(t.closest('#quantity-form')&&t.name==='quantity')quantityPreview();if(t.closest('#recipe-form'))recipePreview();if(t.closest('#use-recipe-form')){if(t.name==='portions'){const r=state.recipes.find(r=>r.id===editor.recipeId),portions=Number(t.value);editor.items=r.items.map(i=>({...i,quantity:Math.round(i.quantity/r.servings*portions*1000000)/1000000}));$('#use-ingredients').innerHTML=ingredientRows(editor.items);}usePreview();}});
document.addEventListener('change',async event=>{const t=event.target;if(t.id==='day-date'&&t.value){selectedDate=t.value;closeEditor();render();}if(t.id==='favorites-only')foodList();if(t.id==='entry-meal'&&editor)editor.meal=t.value;
 if(t.id==='restore-file'&&t.files[0]){const file=t.files[0];t.value='';try{if(file.size>20_000_000)throw Error('O backup excede 20 MB.');const restored=JSON.parse(await file.text());if(!await confirmAction('Restaurar backup?',`Substituir os dados atuais pelo arquivo ${file.name}? Uma cópia dos dados atuais será salva antes da restauração.`))return;busy=true;const result=await api('restore',{state:restored,revision});state=result.state;revision=result.revision;undo=null;closeEditor();render();toast(window.FoodCloud?.enabled?'Backup restaurado. Cópia anterior disponível nas configurações.':'Backup restaurado. Cópia anterior preservada em data/backups.');}catch(e){toast(e.message);}finally{busy=false;}}
});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!form.id||form.closest('dialog'))return;event.preventDefault();if(busy)return;const data=new FormData(form);const val=n=>data.get(n);const num=n=>Number(val(n));
 try{switch(form.id){
 case 'extra-form':openAdd(val('meal').trim());break;
 case 'quantity-form':{const e={id:editor.entryId||id(),food:clone(editor.food),quantity:num('quantity'),meal:val('meal')};if(await change(s=>{const d=dayIn(s),index=d.entries.findIndex(x=>x.id===e.id);if(index>=0)d.entries[index]=e;else d.entries.push(e);d.complete=false;},editor.entryId?'Registro atualizado':'Alimento adicionado'))closeEditor();break;}
 case 'food-form':{const food={id:editor.foodId||id(),name:val('name').trim(),base:num('base'),unit:val('unit'),kcal:num('kcal'),protein:val('protein')===''?null:num('protein'),confidence:val('confidence'),source:val('source').trim(),favorite:data.has('favorite'),sources:editor.sources||[]};const returnMeal=editor.returnMeal,consumed=editor.consumedQuantity??food.base,existing=sameFood(food);if(existing){reuseFood(existing,consumed);break;}if(!editor.foodId)Object.assign(food,normalizeFoodReference(food));if(await change(s=>{const index=s.foods.findIndex(f=>f.id===food.id);if(index>=0)s.foods[index]=food;else s.foods.push(food);},'Alimento salvo')){closeEditor();if(returnMeal){editor={meal:returnMeal};openQuantity(food);$('#quantity-form [name=quantity]').value=consumed;quantityPreview();}}break;}
 case 'recipe-form':collectRecipe();{const recipe=clone(editor.draft);if(await change(s=>{const index=s.recipes.findIndex(r=>r.id===recipe.id);if(index>=0)s.recipes[index]=recipe;else s.recipes.push(recipe);},'Receita salva'))closeEditor();}break;
 case 'use-recipe-form':{collectUse();const entries=editor.items.map(item=>({id:id(),food:clone(foodById(item.foodId)),quantity:item.quantity,meal:val('meal')}));if(await change(s=>{const d=dayIn(s);d.entries.push(...entries);d.complete=false;},'Receita adicionada à refeição'))closeEditor();break;}
 case 'target-form':{const target={date:val('date'),kcal:num('kcal'),protein:num('protein')};const impacts=Object.keys(state.days).some(d=>d>=target.date);if(impacts&&!await confirmAction('Atualizar meta nesse período?','A comparação dos dias registrados a partir dessa data será atualizada. Os alimentos e totais consumidos permanecem iguais.'))return;await change(s=>{s.targets=s.targets.filter(t=>t.date!==target.date);s.targets.push(target);},'Meta salva');break;}
 }}catch(e){formError(e);}
});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#confirm-dialog').open)closeEditor();});
$('#quit').addEventListener('click',async()=>{if(busy)return;if(!await confirmAction('Encerrar aplicativo?','Suas alterações salvas estarão aqui quando você voltar.'))return;try{if(window.FOOD_CLOUD&&window.pywebview){await window.pywebview.api.close();return;}await api('quit',{});closeEditor();main.innerHTML='<div class="empty-state"><h1>Até a próxima refeição.</h1><p>Seus dados estão salvos. Você pode fechar esta janela.</p></div>';$$('button').forEach(b=>b.disabled=true);$('#save-status').textContent='Aplicativo encerrado';window.close();}catch(e){toast(e.message);}});
function sourceLinks(sources){
 if(!Array.isArray(sources))return '';
 return `<div class="ai-sources">${sources.slice(0,3).filter(s=>{try{return new URL(s.url).protocol==='https:';}catch{return false;}}).map(s=>`<a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">Fonte: ${escape(s.title||new URL(s.url).hostname)}</a>`).join('')}</div>`;
}
function assistantBox(food){return `<section class="assistant-box"><h3>Não sabe os valores?</h3><form id="ai-lookup-form"><label class="field">Alimento e quantidade<input id="ai-description" name="description" required minlength="3" maxlength="300" placeholder="Ex.: 150 g de arroz branco cozido" value="${food?escape(`${food.base} ${food.unit} de ${food.name}`):''}"></label><div class="actions"><button class="primary" type="submit">Buscar alimento</button><button type="button" data-ai="settings">Configurar IA</button></div></form><p class="help">Use uma chave de projeto Free Tier. Só esta descrição vai ao Google; dados gratuitos podem melhorar seus produtos.</p><div id="ai-result" class="ai-result" aria-live="polite"></div></section>`;}
function aiSettingsSection(){if(window.FoodCloud?.enabled)return cloudSettingsSection();return `<section class="section"><h2>Assistente de IA</h2><p class="settings-note">Busca calorias e proteína sem sair do cadastro. Resposta curta, sem fonte verificada. Usa Gemini 3.5 Flash-Lite, disponível no Free Tier. Mantenha o projeto sem faturamento para evitar cobranças.</p><p id="ai-status" class="ai-status">Conferindo configuração…</p><form id="ai-key-form"><label class="field">Chave da API Gemini<input name="key" type="password" required autocomplete="off" spellcheck="false" placeholder="Cole sua chave do Google AI Studio" maxlength="4096"><span class="help">Protegida pela sua conta do Windows, fora dos backups. A chave não aparece novamente após salvar.</span></label><div class="actions"><button type="submit" class="primary">Salvar chave</button><button type="button" data-ai="remove-key">Remover chave</button><a href="https://aistudio.google.com/api-keys" target="_blank" rel="noopener noreferrer">Obter chave</a></div><p id="ai-key-error" class="error" role="alert"></p></form></section>`;}
async function loadAiStatus(){const element=$('#ai-status');if(!element)return;try{const result=await api('ai/status');if(element.isConnected)element.textContent=result.configured?'Chave configurada. O acesso será verificado na primeira busca.':'Ainda sem chave. Configure uma vez para ativar a busca.';}catch(e){if(element.isConnected)element.textContent=e.message;}}
document.addEventListener('click',async event=>{
 const button=event.target.closest('[data-ai]');if(!button)return;
 if(button.dataset.ai==='settings'){closeEditor();view='settings';render();$('#ai-key-form input')?.focus();}
 if(button.dataset.ai==='reuse'){const food=foodById(button.dataset.id);if(food)reuseFood(food,editor.savedQuantity);return;}
 if(button.dataset.ai==='use'&&editor?.estimate){
  const original=editor.estimate,existing=sameFood({...original,id:editor.foodId});if(existing){reuseFood(existing,original.base);return;}editor.consumedQuantity=original.base;const result=normalizeFoodReference(original),form=$('#food-form');
  for(const field of ['name','base','unit','kcal','protein'])form.elements[field].value=result[field]??'';
  form.elements.confidence.value='estimate';
  form.elements.source.value=`Estimativa por IA, sem fonte verificada${result.note?' · '+result.note:''}`.slice(0,500);
  editor.sources=clone(result.sources);
  button.textContent='Estimativa aplicada';button.disabled=true;
  form.elements.name.focus();toast('Valores preenchidos. Confira e salve o alimento.');
 }
 if(button.dataset.ai==='remove-key'){
  if(!await confirmAction('Remover a chave deste app?','A busca com IA será desativada. Seus alimentos e refeições continuam salvos.'))return;
  button.disabled=true;try{await api('ai/remove',{});await loadAiStatus();toast('Chave removida deste computador.');}catch(e){toast(e.message);}finally{button.disabled=false;}
 }
});
document.addEventListener('submit',async event=>{
 const form=event.target;
 if(form.id==='ai-key-form'){
  event.preventDefault();const button=$('button[type=submit]',form),input=form.elements.key,error=$('#ai-key-error');if(button.disabled)return;
  button.disabled=true;error.textContent='';
  try{await api('ai/configure',{key:input.value.trim()});input.value='';await loadAiStatus();toast('Chave protegida e salva. Você já pode buscar alimentos.');}
  catch(e){error.textContent=e.message;}finally{button.disabled=false;}
 }
 if(form.id==='ai-lookup-form'){
  event.preventDefault();const context=editor,button=$('button[type=submit]',form),query=$('#ai-description'),output=$('#ai-result');
  if(button.disabled)return;const description=query.value.trim();button.disabled=true;button.textContent='Pesquisando…';query.readOnly=true;
  context.estimate=null;output.innerHTML='<p>Estimando calorias e proteína…</p>';
  try{if(savedFoodResult(description,output))return;const result=await api('ai/estimate',{description});if(editor!==context||!output.isConnected)return;
   if(result.status!=='estimate'){output.innerHTML=`<p>${escape(result.question)}</p>`;query.focus();return;}
   if(savedFoodResult(`${result.base} ${result.unit} de ${result.name}`,output))return;
   context.estimate=result;
   output.innerHTML=`<p>${escape(result.name)} · ${fmt(result.base,2)} ${escape(result.unit)}</p><p><strong>≈ ${fmt(result.kcal)} kcal</strong> · ${result.protein===null?'proteína não informada':fmt(result.protein,1)+' g de proteína'}</p>${result.note?`<p class="muted">${escape(result.note)}</p>`:''}<p class="help">Estimativa por IA, sem fonte verificada.</p><div class="actions"><button class="secondary" data-ai="use">Usar estimativa</button></div>`;
  }catch(e){if(editor===context&&output.isConnected)output.innerHTML=`<p class="error">${escape(e.message)}</p>`;}
  finally{button.disabled=false;button.textContent='Buscar alimento';query.readOnly=false;}
 }
});
api('state').then(result=>{state=result.state;revision=result.revision;render();updateSaveStatus();}).catch(e=>{main.innerHTML=`<div class="empty-state"><h1>Não foi possível abrir o diário</h1><p>${escape(e.message)}</p><p>Feche a janela e abra o aplicativo novamente.</p></div>`;});

window.addEventListener('pywebviewready',()=>{document.body.classList.add('desktop');
 document.querySelectorAll('[data-window]').forEach(button=>button.addEventListener('click',async()=>{
  try{
   if(button.dataset.window==='close'){$('#quit').click();return;}
   await window.pywebview.api[button.dataset.window]();
  }catch{toast('Não foi possível controlar a janela. Tente novamente.');}
 }));
 document.querySelector('.window-drag').addEventListener('dblclick',()=>window.pywebview.api.maximize());
});

function updateSaveStatus(){
 const message=window.FoodCloud?.enabled?FoodCloud.status():'Todas as alterações salvas';$('#save-status').textContent=message;
 const indicator=$('#sync-indicator');if(indicator&&window.FoodCloud?.enabled){indicator.hidden=false;indicator.textContent=message;}
}
async function refreshCloudView(){
 if(!window.FoodCloud?.enabled||editor||busy)return;
 const result=await FoodCloud.api('state');state=result.state;revision=result.revision;render();updateSaveStatus();
}
function cloudSettingsSection(){return `<section class="section"><h2>Sua conta e sincronização</h2><p class="settings-note">${escape(FoodCloud.user?.email||'')}<br>${escape(FoodCloud.status())}</p><div class="actions"><button class="secondary" data-cloud="sync">Sincronizar agora</button><button data-cloud="login">Entrar novamente</button><button data-cloud="logout">Sair deste aparelho</button></div><div id="cloud-conflicts">${FoodCloud.conflicts.map((c,i)=>`<div class="conflict-item"><h3>Escolha qual versão manter</h3><p>${escape(c.key.split('/')[0]==='entries'?'Registro de refeição':c.key.split('/')[0]==='foods'?'Alimento':'Alteração no diário')}</p><p><b>Neste aparelho:</b> ${escape(conflictSummary(c.local))}</p><p><b>Na nuvem:</b> ${escape(conflictSummary(c.remote))}</p><div class="actions"><button data-cloud="local" data-index="${i}">Manter deste aparelho</button><button data-cloud="remote" data-index="${i}">Usar da nuvem</button></div></div>`).join('')}</div>${FoodCloud.backup?'<button data-cloud="previous-backup">Baixar cópia anterior à restauração</button>':''}</section><section class="section"><h2>Assistente de IA</h2><p id="ai-status" class="ai-status">Conferindo configuração…</p><p class="settings-note">A chave fica no servidor. Fotos e descrições são enviadas ao Google somente ao pedir uma estimativa. O Food Tracker não guarda as fotos. Limite do app: 30 consultas por dia; a cota do Gemini também se aplica.</p></section><section class="section"><h2>Instalar no iPhone</h2><p class="settings-note">No Safari, abra Compartilhar → Adicionar à Tela de Início. Ative Abrir como App da Web, se essa opção aparecer. Use sempre este mesmo endereço para acessar seu diário.</p></section>`;}
function conflictSummary(v){if(v===null)return 'Excluído';if(v.food)return `${v.food.name} · ${fmt(v.quantity,2)} ${v.food.unit} · ${v.meal} · ${v.date}`;if(v.name)return `${v.name}${v.kcal!==undefined?' · '+fmt(v.kcal)+' kcal por '+v.base+' '+v.unit:''}`;if(v.date)return `${v.date} · ${v.kcal} kcal · ${v.protein} g`;return v.complete?'Dia completo':'Dia em registro';}
window.addEventListener('food-cloud-status',updateSaveStatus);
window.addEventListener('food-cloud-updated',refreshCloudView);
$('#sync-indicator').addEventListener('click',()=>{view='settings';closeEditor();render();});
document.addEventListener('click',async e=>{
 const button=e.target.closest('[data-cloud]');if(!button)return;button.disabled=true;
 try{
  const action=button.dataset.cloud;
  if(action==='sync')await FoodCloud.synchronize();
  if(action==='login'){await FoodCloud.relogin();await refreshCloudView();}
  if(action==='logout'&&await confirmAction('Sair deste aparelho?','Os registros sincronizados permanecem na sua conta. A cópia deste aparelho será removida.'))await FoodCloud.logout();
  if(action==='local'||action==='remote'){const c=FoodCloud.conflicts[Number(button.dataset.index)];if(c)await FoodCloud.resolveConflict(c.key,action);}
  if(action==='previous-backup'){const url=URL.createObjectURL(new Blob([JSON.stringify(FoodCloud.backup,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='food-tracker-antes-restauracao.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 }catch(error){toast(error.message);}finally{button.disabled=false;}
});
if(window.FOOD_CLOUD&&'serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
